-- YouTube Room — initial schema.
--
-- Conventions:
--   * Primary keys are UUIDv7, generated by the application. They are
--     time-ordered, so B-tree inserts stay sequential and `ORDER BY id` is a
--     valid chronological sort (ADR 0003).
--   * Timestamps are `timestamptz`, always UTC.
--   * Soft deletes only where a hard delete would orphan history worth keeping.

-- ---------------------------------------------------------------------------
-- Users
-- ---------------------------------------------------------------------------

CREATE TABLE users (
    id             uuid PRIMARY KEY,
    kind           text        NOT NULL CHECK (kind IN ('google', 'guest')),

    -- Google's stable subject identifier. Never the email: emails get reassigned.
    google_sub     text        UNIQUE,
    email          text,

    display_name   text        NOT NULL CHECK (char_length(display_name) BETWEEN 2 AND 32),
    avatar_url     text,

    created_at     timestamptz NOT NULL DEFAULT now(),
    last_seen_at   timestamptz NOT NULL DEFAULT now(),

    -- A Google account must carry its subject; a guest must not.
    CONSTRAINT users_identity_matches_kind CHECK (
        (kind = 'google' AND google_sub IS NOT NULL) OR
        (kind = 'guest'  AND google_sub IS NULL)
    )
);

CREATE INDEX users_last_seen_idx ON users (last_seen_at DESC);
CREATE UNIQUE INDEX users_email_lower_idx ON users (lower(email)) WHERE email IS NOT NULL;

-- ---------------------------------------------------------------------------
-- Sessions
-- ---------------------------------------------------------------------------

-- Refresh tokens are opaque and stored only as SHA-256 hashes, so a database
-- leak does not hand over live sessions. Rotation is enforced by `consumed_at`:
-- presenting an already-consumed token revokes its whole family (ADR 0007).
CREATE TABLE refresh_tokens (
    id           uuid PRIMARY KEY,
    user_id      uuid        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    token_hash   text        NOT NULL UNIQUE,

    -- All descendants of one login share a family; reuse detection kills it whole.
    family_id    uuid        NOT NULL,

    issued_at    timestamptz NOT NULL DEFAULT now(),
    expires_at   timestamptz NOT NULL,
    consumed_at  timestamptz,
    revoked_at   timestamptz,

    user_agent   text,
    ip_address   inet
);

CREATE INDEX refresh_tokens_user_idx   ON refresh_tokens (user_id);
CREATE INDEX refresh_tokens_family_idx ON refresh_tokens (family_id);
CREATE INDEX refresh_tokens_expiry_idx ON refresh_tokens (expires_at);

-- ---------------------------------------------------------------------------
-- Rooms
-- ---------------------------------------------------------------------------

CREATE TABLE rooms (
    id                  uuid PRIMARY KEY,
    slug                text        NOT NULL UNIQUE,
    name                text        NOT NULL CHECK (char_length(name) BETWEEN 2 AND 60),
    topic               text        CHECK (topic IS NULL OR char_length(topic) <= 200),

    visibility          text        NOT NULL DEFAULT 'private'
                                    CHECK (visibility IN ('public', 'private', 'unlisted')),
    category            text        NOT NULL DEFAULT 'general'
                                    CHECK (category IN ('general','anime','gaming','programming','music','movies','education')),

    host_id             uuid        NOT NULL REFERENCES users (id) ON DELETE CASCADE,

    -- Argon2id. NULL means no password.
    password_hash       text,

    max_participants    integer     NOT NULL DEFAULT 25 CHECK (max_participants BETWEEN 2 AND 100),

    -- Behavioural toggles live in jsonb so adding one is not a migration.
    settings            jsonb       NOT NULL DEFAULT '{
                                      "allowGuestControl": false,
                                      "allowGuestQueue": true,
                                      "voteSkipRatio": 0.5,
                                      "autoAdvance": true,
                                      "shuffle": false,
                                      "theme": "midnight"
                                    }'::jsonb,

    -- Maintained by the realtime hub; the directory reads it instead of
    -- counting live connections across nodes.
    active_participants integer     NOT NULL DEFAULT 0,

    created_at          timestamptz NOT NULL DEFAULT now(),
    updated_at          timestamptz NOT NULL DEFAULT now(),
    last_active_at      timestamptz NOT NULL DEFAULT now(),
    deleted_at          timestamptz
);

-- The public directory is the hottest read. A partial index keeps it off the
-- long tail of private rooms entirely.
CREATE INDEX rooms_directory_idx
    ON rooms (last_active_at DESC, active_participants DESC)
    WHERE visibility = 'public' AND deleted_at IS NULL;

CREATE INDEX rooms_category_idx
    ON rooms (category, last_active_at DESC)
    WHERE visibility = 'public' AND deleted_at IS NULL;

CREATE INDEX rooms_host_idx ON rooms (host_id) WHERE deleted_at IS NULL;

-- Full-text search over name + topic for the directory search box.
CREATE INDEX rooms_search_idx
    ON rooms USING gin (
        to_tsvector('english', name || ' ' || coalesce(topic, ''))
    ) WHERE visibility = 'public' AND deleted_at IS NULL;

-- ---------------------------------------------------------------------------
-- Membership
-- ---------------------------------------------------------------------------

CREATE TABLE room_members (
    room_id      uuid        NOT NULL REFERENCES rooms (id) ON DELETE CASCADE,
    user_id      uuid        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    role         text        NOT NULL DEFAULT 'member'
                             CHECK (role IN ('host', 'moderator', 'member', 'guest')),
    joined_at    timestamptz NOT NULL DEFAULT now(),
    last_seen_at timestamptz NOT NULL DEFAULT now(),
    banned_at    timestamptz,
    banned_by    uuid        REFERENCES users (id) ON DELETE SET NULL,

    PRIMARY KEY (room_id, user_id)
);

CREATE INDEX room_members_user_idx ON room_members (user_id, last_seen_at DESC);
-- Exactly one host per room, enforced by the database rather than by convention.
CREATE UNIQUE INDEX room_members_single_host_idx
    ON room_members (room_id) WHERE role = 'host';

CREATE TABLE room_invites (
    id          uuid PRIMARY KEY,
    room_id     uuid        NOT NULL REFERENCES rooms (id) ON DELETE CASCADE,
    code        text        NOT NULL UNIQUE,
    created_by  uuid        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    created_at  timestamptz NOT NULL DEFAULT now(),
    expires_at  timestamptz,
    max_uses    integer     CHECK (max_uses IS NULL OR max_uses > 0),
    uses        integer     NOT NULL DEFAULT 0
);

CREATE INDEX room_invites_room_idx ON room_invites (room_id);

-- ---------------------------------------------------------------------------
-- Queue
-- ---------------------------------------------------------------------------

-- `position` is a fractional index: inserting between two items is one UPDATE
-- rather than renumbering the tail (see util::fractional_position).
CREATE TABLE queue_items (
    id               uuid PRIMARY KEY,
    room_id          uuid             NOT NULL REFERENCES rooms (id) ON DELETE CASCADE,
    video_id         text             NOT NULL CHECK (char_length(video_id) = 11),
    title            text             NOT NULL,
    channel_title    text             NOT NULL DEFAULT '',
    duration_seconds integer          NOT NULL DEFAULT 0,
    thumbnail_url    text             NOT NULL DEFAULT '',
    added_by         uuid             REFERENCES users (id) ON DELETE SET NULL,
    added_at         timestamptz      NOT NULL DEFAULT now(),
    position         double precision NOT NULL,
    played_at        timestamptz
);

CREATE INDEX queue_items_room_position_idx
    ON queue_items (room_id, position) WHERE played_at IS NULL;
CREATE INDEX queue_items_room_history_idx
    ON queue_items (room_id, played_at DESC) WHERE played_at IS NOT NULL;

-- ---------------------------------------------------------------------------
-- Chat
-- ---------------------------------------------------------------------------

CREATE TABLE chat_messages (
    id          uuid PRIMARY KEY,
    room_id     uuid        NOT NULL REFERENCES rooms (id) ON DELETE CASCADE,
    author_id   uuid        REFERENCES users (id) ON DELETE SET NULL,
    body        text        NOT NULL CHECK (char_length(body) BETWEEN 1 AND 2000),
    sent_at     timestamptz NOT NULL DEFAULT now(),
    edited_at   timestamptz,
    reply_to    uuid        REFERENCES chat_messages (id) ON DELETE SET NULL,
    pinned      boolean     NOT NULL DEFAULT false,
    -- Non-null for generated messages ("Sam joined"), which have no author.
    system_kind text        CHECK (system_kind IS NULL OR system_kind IN
                            ('join','leave','skip','host_changed','video_changed')),
    mentions    uuid[]      NOT NULL DEFAULT '{}',
    deleted_at  timestamptz
);

-- Paging backwards through history is the only access pattern that matters.
CREATE INDEX chat_messages_room_time_idx
    ON chat_messages (room_id, sent_at DESC) WHERE deleted_at IS NULL;
CREATE INDEX chat_messages_pinned_idx
    ON chat_messages (room_id) WHERE pinned AND deleted_at IS NULL;

-- ---------------------------------------------------------------------------
-- Personal history
-- ---------------------------------------------------------------------------

CREATE TABLE watch_history (
    id               uuid PRIMARY KEY,
    user_id          uuid             NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    room_id          uuid             REFERENCES rooms (id) ON DELETE SET NULL,
    video_id         text             NOT NULL,
    title            text             NOT NULL,
    thumbnail_url    text             NOT NULL DEFAULT '',
    position_seconds double precision NOT NULL DEFAULT 0,
    duration_seconds integer          NOT NULL DEFAULT 0,
    watched_at       timestamptz      NOT NULL DEFAULT now()
);

-- One row per user/video: rewatching updates in place, so "continue watching"
-- never shows the same video twice.
CREATE UNIQUE INDEX watch_history_user_video_idx ON watch_history (user_id, video_id);
CREATE INDEX watch_history_recent_idx ON watch_history (user_id, watched_at DESC);

CREATE TABLE bookmarks (
    id               uuid PRIMARY KEY,
    user_id          uuid             NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    video_id         text             NOT NULL,
    title            text             NOT NULL,
    thumbnail_url    text             NOT NULL DEFAULT '',
    -- Non-null for a timestamp bookmark ("that bit at 4:12").
    position_seconds double precision,
    note             text CHECK (note IS NULL OR char_length(note) <= 280),
    created_at       timestamptz      NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX bookmarks_user_video_position_idx
    ON bookmarks (user_id, video_id, coalesce(position_seconds, -1));

CREATE TABLE room_favorites (
    user_id    uuid        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    room_id    uuid        NOT NULL REFERENCES rooms (id) ON DELETE CASCADE,
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, room_id)
);

-- ---------------------------------------------------------------------------
-- Operations
-- ---------------------------------------------------------------------------

-- Append-only. Moderation actions and ownership changes need to be answerable
-- after the fact, and refresh-token reuse detection writes here.
CREATE TABLE audit_log (
    id         uuid PRIMARY KEY,
    actor_id   uuid        REFERENCES users (id) ON DELETE SET NULL,
    room_id    uuid        REFERENCES rooms (id) ON DELETE SET NULL,
    action     text        NOT NULL,
    metadata   jsonb       NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX audit_log_room_idx  ON audit_log (room_id, created_at DESC);
CREATE INDEX audit_log_actor_idx ON audit_log (actor_id, created_at DESC);

CREATE TABLE feature_flags (
    key         text PRIMARY KEY,
    enabled     boolean     NOT NULL DEFAULT false,
    -- Percentage rollout, allowlists, and any flag-specific configuration.
    payload     jsonb       NOT NULL DEFAULT '{}'::jsonb,
    description text        NOT NULL DEFAULT '',
    updated_at  timestamptz NOT NULL DEFAULT now()
);

INSERT INTO feature_flags (key, enabled, description) VALUES
    ('voice_chat',      true,  'WebRTC voice in rooms'),
    ('vote_skip',       true,  'Non-hosts can vote to skip the current video'),
    ('reactions',       true,  'Floating emoji reaction bursts'),
    ('scheduled_rooms', false, 'Rooms that open at a future time'),
    ('livekit_sfu',     false, 'Route voice through LiveKit instead of mesh');

-- ---------------------------------------------------------------------------
-- Triggers
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION touch_updated_at() RETURNS trigger AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER rooms_touch_updated_at
    BEFORE UPDATE ON rooms
    FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
